// import { jsPDF } from "jspdf";

/**
 * BrandExporter Utility
 * Generates a professional 4-page PDF "Brand Bible" from AI results.
 */
export const exportBrandToPDF = async (brandData) => {
  const doc = new jsPDF();
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();

  // Helper: Draw Header
  const drawHeader = (title, pageNum) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`IDEA2BRAND AI // ${brandData.name.toUpperCase()}`, margin, 15);
    doc.text(`PAGE ${pageNum}`, pageWidth - margin - 15, 15);
    doc.setDrawColor(200);
    doc.line(margin, 18, pageWidth - margin, 18);
  };

  // --- PAGE 1: COVER ---
  doc.setFillColor(15, 23, 42); // Slate 950
  doc.rect(0, 0, pageWidth, doc.internal.pageSize.getHeight(), 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(60);
  doc.setFont("helvetica", "bold");
  doc.text(brandData.name.toUpperCase().charAt(0), pageWidth / 2, 80, { align: "center" });

  doc.setFontSize(40);
  doc.text(brandData.name, pageWidth / 2, 120, { align: "center" });

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.text(brandData.identity.tagline.toUpperCase(), pageWidth / 2, 140, { align: "center" });

  doc.setFontSize(10);
  doc.text("OFFICIAL BRAND BIBLE // GENERATED BY IDEA2BRAND AI", pageWidth / 2, 260, { align: "center" });

  // --- PAGE 2: IDENTITY ---
  doc.addPage();
  drawHeader("VISUAL IDENTITY", 2);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(24);
  doc.text("Visual Identity", margin, 40);

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text("Logo Concept", margin, 55);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text(brandData.identity.logoStyle.toUpperCase(), margin, 62);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text("Color Palette", margin, 85);

  // Draw Color Boxes
  brandData.identity.colors.hex.forEach((color, i) => {
    const x = margin + (i * 45);
    const y = 95;
    doc.setFillColor(color);
    doc.rect(x, y, 35, 20, 'F');
    doc.setFontSize(8);
    doc.setTextColor(0);
    doc.text(color, x, y + 25);
  });

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text("Typography", margin, 140);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.text(`Primary: ${brandData.identity.typography.primary}`, margin, 150);
  doc.text(`Secondary: ${brandData.identity.typography.secondary}`, margin, 160);

  // --- PAGE 3: BRAND VOICE ---
  doc.addPage();
  drawHeader("BRAND VOICE", 3);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(24);
  doc.text("Brand Voice", margin, 40);

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text("Mission Statement", margin, 55);
  doc.setTextColor(0);
  doc.setFontSize(11);
  const missionLines = doc.splitTextToSize(brandData.mission.about, pageWidth - (margin * 2));
  doc.text(missionLines, margin, 65);

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text("Elevator Pitch", margin, 110);
  doc.setTextColor(0);
  doc.setFont("helvetica", "italic");
  const pitchLines = doc.splitTextToSize(`"${brandData.copy.elevatorPitch}"`, pageWidth - (margin * 2));
  doc.text(pitchLines, margin, 120);

  // --- PAGE 4: STRATEGY ---
  doc.addPage();
  drawHeader("GROWTH STRATEGY", 4);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(24);
  doc.text("Strategic Roadmap", margin, 40);

  brandData.strategy.forEach((s, i) => {
    const y = 60 + (i * 35);
    doc.setFillColor(241, 245, 249); // Slate 100
    doc.rect(margin, y - 5, pageWidth - (margin * 2), 25, 'F');

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(37, 99, 235); // Blue 600
    doc.text(s.goal.toUpperCase(), margin + 5, y + 5);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85); // Slate 700
    doc.text(s.action, margin + 5, y + 15);
  });

  doc.save(`${brandData.name}_BrandBible.pdf`);
};
